use std::{ops::Not, path::Path, sync::Arc};

use anyhow::Context;
use rcgen::{CertifiedKey, KeyPair};
use tokio_rustls::{
    TlsAcceptor, TlsConnector,
    rustls::{
        ClientConfig, RootCertStore, ServerConfig, SupportedProtocolVersion,
        pki_types::{CertificateDer, PrivateKeyDer, ServerName, pem::PemObject},
        version::TLS13,
    },
};

/// Subject alternative name of the certificate generated by [`generate_cert`].
const CERT_SAN: &str = "echo-server";

/// The only TLS version the benchmarked protocols speak.
const PROTOCOL_VERSIONS: &[&SupportedProtocolVersion] = &[&TLS13];

/// The ALPN both sides offer.
///
/// Only QUIC needs it - its handshake is the connection's, so there is no
/// upgrade request to name the protocol in - but setting it on the shared
/// configs keeps the two paths from drifting.
const ALPN: &[u8] = b"rammux-perf";

/// Generates a self-signed certificate to be used by the echo server.
pub fn generate_cert() -> anyhow::Result<CertifiedKey<KeyPair>> {
    rcgen::generate_simple_self_signed(vec![CERT_SAN.to_string()])
        .context("failed to generate a self-signed certificate")
}

/// The name that [`generate_cert`] certifies.
pub fn server_name() -> ServerName<'static> {
    ServerName::try_from(CERT_SAN).expect("CERT_SAN is a valid DNS name")
}

/// A certificate chain and its private key, as read from a PEM bundle.
///
/// This is the file [`generate_cert`] produces, in the layout the `generate-cert`
/// subcommand prints it: the certificate first, its private key second. Both
/// peers read the same bundle, because nothing but the certificate itself
/// certifies a self-signed identity.
pub struct CertBundle {
    chain: Vec<CertificateDer<'static>>,
    key: PrivateKeyDer<'static>,
}

impl CertBundle {
    /// Reads a bundle from a PEM file.
    ///
    /// Fails if the file holds no certificate, or no private key.
    pub fn read(path: &Path) -> anyhow::Result<Self> {
        let pem = std::fs::read(path)
            .with_context(|| format!("failed to read the PEM bundle at {}", path.display()))?;

        let chain = CertificateDer::pem_slice_iter(&pem)
            .collect::<Result<Vec<_>, _>>()
            .with_context(|| format!("failed to parse certificates from {}", path.display()))?;
        anyhow::ensure!(
            chain.is_empty().not(),
            "{} holds no certificate",
            path.display(),
        );

        let key = PrivateKeyDer::from_pem_slice(&pem)
            .with_context(|| format!("failed to parse a private key from {}", path.display()))?;

        Ok(Self { chain, key })
    }

    /// Builds a [`TlsAcceptor`] serving this bundle's certificate.
    pub fn acceptor(&self) -> anyhow::Result<TlsAcceptor> {
        Ok(TlsAcceptor::from(Arc::new(self.server_config()?)))
    }

    /// The server side as `rustls` sees it, for a caller that needs the config
    /// itself rather than an acceptor - QUIC, whose handshake is its own.
    pub fn server_config(&self) -> anyhow::Result<ServerConfig> {
        let mut config = ServerConfig::builder_with_protocol_versions(PROTOCOL_VERSIONS)
            .with_no_client_auth()
            .with_single_cert(self.chain.clone(), self.key.clone_key())
            .context("failed to build a TLS server config from the bundle")?;
        config.alpn_protocols = vec![ALPN.to_vec()];
        Ok(config)
    }

    /// Builds a [`TlsConnector`] trusting this bundle's certificate, and nothing else.
    ///
    /// Connect with [`server_name`]; no other name is certified.
    pub fn connector(&self) -> anyhow::Result<TlsConnector> {
        Ok(TlsConnector::from(Arc::new(self.client_config()?)))
    }

    /// The client side as `rustls` sees it, for QUIC.
    pub fn client_config(&self) -> anyhow::Result<ClientConfig> {
        let mut roots = RootCertStore::empty();
        for cert in &self.chain {
            roots
                .add(cert.clone())
                .context("failed to pin the bundle's certificate as a trust root")?;
        }
        let mut config = ClientConfig::builder_with_protocol_versions(PROTOCOL_VERSIONS)
            .with_root_certificates(roots)
            .with_no_client_auth();
        config.alpn_protocols = vec![ALPN.to_vec()];
        Ok(config)
    }
}

#[cfg(test)]
mod test {
    use std::io::Write;

    use tempfile::NamedTempFile;
    use tokio::io::{AsyncReadExt, AsyncWriteExt};
    use tokio_rustls::rustls::ProtocolVersion;

    use super::*;

    const PAYLOAD: &[u8; 5] = b"hello";

    #[tokio::test]
    async fn bundle_works() {
        let file = {
            let cert = generate_cert().unwrap();
            let mut file = NamedTempFile::new().unwrap();
            file.write_all(cert.cert.pem().as_bytes()).unwrap();
            file.write_all(cert.signing_key.serialize_pem().as_bytes())
                .unwrap();
            file.flush().unwrap();
            file
        };
        let bundle = CertBundle::read(file.path()).unwrap();
        let acceptor = bundle.acceptor().unwrap();
        let connector = bundle.connector().unwrap();

        let (io_1, io_2) = tokio::io::duplex(16 * 1024);

        tokio::join!(
            async {
                let mut stream = connector.connect(server_name(), io_1).await.unwrap();
                assert_eq!(
                    stream.get_ref().1.protocol_version(),
                    Some(ProtocolVersion::TLSv1_3),
                );
                stream.write_all(PAYLOAD).await.unwrap();
                stream.flush().await.unwrap();
                let mut buf = [0; PAYLOAD.len()];
                stream.read_exact(&mut buf).await.unwrap();
                assert_eq!(&buf, PAYLOAD);
            },
            async {
                let mut stream = acceptor.accept(io_2).await.unwrap();
                assert_eq!(
                    stream.get_ref().1.protocol_version(),
                    Some(ProtocolVersion::TLSv1_3),
                );
                let mut buf = [0; PAYLOAD.len()];
                stream.read_exact(&mut buf).await.unwrap();
                assert_eq!(&buf, PAYLOAD);
                stream.write_all(&buf).await.unwrap();
                stream.flush().await.unwrap();
            },
        );
    }
}
